name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --frozen-lockfile
      - name: Build
        run: npm run build
      # - uses: actions/configure-pages@v3
      #   with:
      #     token: ${{ secrets.BLOG }}
      #     # publish_dir: .vitepress/dist
      # - uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: .vitepress/dist
      # - name: Deploy
      #   id: deployment
      #   uses: actions/deploy-pages@v1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG }}
          publish_dir: .vitepress/dist
